import os
import django
import sys

# Add the current directory to the Python path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Set up Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'wayantrails_backend.settings')
django.setup()

from resorts.models import Resort
from homestays.models import Homestay
from django.utils import timezone

# Clear existing data
Resort.objects.all().delete()
Homestay.objects.all().delete()

# Create Resorts
resorts_data = [
    {
        "name": "Vythiri Village Resort",
        "slug": "vythiri-village-resort",
        "description": "Vythiri Village is a premium eco-resort nestled in the lush rainforests of Wayanad. Spread across 150 acres of plantation land, it offers luxury cottages with stunning views of the Western Ghats.",
        "short_description": "Luxury eco-resort in 150 acres of rainforest with cottages, spa and infinity pool",
        "resort_type": "eco",
        "star_rating": 5,
        "phone": "+91 4936 255366",
        "email": "info@vythirivillage.com",
        "website": "https://vythirivillage.com",
        "total_rooms": 45,
        "price_range_min": "8500",
        "price_range_max": "25000",
        "check_in_time": "14:00:00",
        "check_out_time": "11:00:00",
        "cancellation_policy": "Free cancellation up to 48 hours before check-in.",
        "address_line_1": "Lakkidi P.O., Vythiri",
        "city": "Vythiri",
        "state": "Kerala",
        "postal_code": "673576",
        "country": "India",
        "latitude": "11.5408",
        "longitude": "76.0297",
        "cover_image": "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800",
        "gallery_images": ["https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800"],
        "is_active": True,
        "is_featured": True,
        "is_verified": True,
        "commission_rate": "15.00",
    },
    {
        "name": "Wayanad Silverwoods",
        "slug": "wayanad-silverwoods",
        "description": "Silverwoods is a boutique resort offering a perfect blend of luxury and nature. Located in Kalpetta, it features elegantly designed rooms with modern amenities.",
        "short_description": "Boutique resort with elegant rooms, pool, and multi-cuisine dining in Kalpetta",
        "resort_type": "boutique",
        "star_rating": 4,
        "phone": "+91 4936 204492",
        "email": "reservations@silverwoods.in",
        "website": "https://wayanadsilverwoods.com",
        "total_rooms": 32,
        "price_range_min": "5500",
        "price_range_max": "12000",
        "check_in_time": "13:00:00",
        "check_out_time": "11:00:00",
        "cancellation_policy": "Free cancellation up to 24 hours before check-in.",
        "address_line_1": "Vythiri Road, Kalpetta",
        "city": "Kalpetta",
        "state": "Kerala",
        "postal_code": "673122",
        "country": "India",
        "latitude": "11.6085",
        "longitude": "76.0856",
        "cover_image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        "gallery_images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
        "is_active": True,
        "is_featured": True,
        "is_verified": True,
        "commission_rate": "12.00",
    },
    {
        "name": "Pepper Trail Resort & Spa",
        "slug": "pepper-trail-resort-spa",
        "description": "Pepper Trail is a luxury wellness resort set amidst spice plantations in Meppadi. The resort offers spacious villas, an ayurvedic spa, yoga pavilion.",
        "short_description": "Luxury wellness resort with villas, ayurvedic spa, and organic dining",
        "resort_type": "luxury",
        "star_rating": 5,
        "phone": "+91 4936 248800",
        "email": "stay@peppertrail.com",
        "website": "https://peppertrail.com",
        "total_rooms": 28,
        "price_range_min": "12000",
        "price_range_max": "35000",
        "check_in_time": "14:00:00",
        "check_out_time": "12:00:00",
        "cancellation_policy": "Free cancellation up to 7 days before check-in.",
        "address_line_1": "Meppadi, Kalpetta Road",
        "city": "Meppadi",
        "state": "Kerala",
        "postal_code": "673577",
        "country": "India",
        "latitude": "11.5163",
        "longitude": "76.1148",
        "cover_image": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
        "gallery_images": ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
        "is_active": True,
        "is_featured": True,
        "is_verified": True,
        "commission_rate": "18.00",
    },
    {
        "name": "The Windflower Resort & Spa",
        "slug": "windflower-resort-spa-vythiri",
        "description": "The Windflower is a family-friendly resort located in the heart of Vythiri. With spacious cottages, kids play area, outdoor activities.",
        "short_description": "Family-friendly resort with cottages, kids activities, spa and mountain views",
        "resort_type": "family",
        "star_rating": 4,
        "phone": "+91 4936 255300",
        "email": "vythiri@thewindflower.com",
        "website": "https://thewindflower.com/vythiri",
        "total_rooms": 38,
        "price_range_min": "6500",
        "price_range_max": "18000",
        "check_in_time": "14:00:00",
        "check_out_time": "11:00:00",
        "cancellation_policy": "Free cancellation up to 48 hours before check-in.",
        "address_line_1": "Vythiri, Lakkidi Road",
        "city": "Vythiri",
        "state": "Kerala",
        "postal_code": "673576",
        "country": "India",
        "latitude": "11.5345",
        "longitude": "76.0312",
        "cover_image": "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
        "gallery_images": ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"],
        "is_active": True,
        "is_featured": False,
        "is_verified": True,
        "commission_rate": "15.00",
    },
    {
        "name": "Wild Planet Resort",
        "slug": "wild-planet-resort-wayanad",
        "description": "Wild Planet is an adventure-focused resort offering unique experiences like zip-lining, rock climbing, and wildlife safaris.",
        "short_description": "Adventure resort with zip-lining, wildlife safaris, and rustic cottages",
        "resort_type": "adventure",
        "star_rating": 3,
        "phone": "+91 4936 222444",
        "email": "info@wildplanetresort.com",
        "website": "https://wildplanetresort.com",
        "total_rooms": 22,
        "price_range_min": "4500",
        "price_range_max": "9000",
        "check_in_time": "13:00:00",
        "check_out_time": "11:00:00",
        "cancellation_policy": "Free cancellation up to 3 days before check-in.",
        "address_line_1": "Muthanga Wildlife Sanctuary Road",
        "city": "Sultan Bathery",
        "state": "Kerala",
        "postal_code": "673592",
        "country": "India",
        "latitude": "11.6833",
        "longitude": "76.2833",
        "cover_image": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
        "gallery_images": ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800"],
        "is_active": True,
        "is_featured": False,
        "is_verified": True,
        "commission_rate": "10.00",
    },
]

print("Creating resorts...")
for data in resorts_data:
    Resort.objects.create(**data)
print(f"Created {len(resorts_data)} resorts!")

# Create Homestays
homestays_data = [
    {
        "name": "Green Gates Homestay",
        "slug": "green-gates-homestay-vythiri",
        "description": "Green Gates is a traditional Kerala homestay run by the friendly Mathew family. Experience authentic Wayanad hospitality.",
        "short_description": "Traditional Kerala homestay in coffee plantation with home-cooked meals",
        "homestay_type": "traditional",
        "host_name": "Mathew Joseph",
        "host_phone": "+91 94470 12345",
        "host_email": "greengates@gmail.com",
        "host_bio": "We are the Mathew family, third-generation coffee planters in Wayanad.",
        "host_languages": ["Malayalam", "English", "Hindi"],
        "total_rooms": 4,
        "total_bathrooms": 4,
        "family_size": 5,
        "max_guests": 12,
        "price_per_night": "3500",
        "extra_person_charge": "800",
        "provides_meals": True,
        "meal_types": ["Breakfast", "Lunch", "Dinner"],
        "cooking_experience": True,
        "local_guide_service": True,
        "check_in_time": "12:00:00",
        "check_out_time": "11:00:00",
        "house_rules": "No smoking inside. No loud music after 10 PM.",
        "cancellation_policy": "Free cancellation up to 3 days before check-in.",
        "pet_friendly": False,
        "children_friendly": True,
        "elderly_friendly": True,
        "cultural_activities": ["Traditional cooking class", "Village walk"],
        "farm_activities": ["Coffee picking", "Spice plantation tour"],
        "nearby_attractions": ["Chembra Peak 8km", "Soochipara Falls 12km"],
        "address_line_1": "Coffee Estate Road, Pozhuthana",
        "city": "Vythiri",
        "state": "Kerala",
        "postal_code": "673576",
        "country": "India",
        "latitude": "11.5298",
        "longitude": "76.0421",
        "cover_image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        "gallery_images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
        "is_active": True,
        "is_featured": True,
        "is_verified": True,
        "commission_rate": "10.00",
    },
    {
        "name": "Tranquil Farmstay Wayanad",
        "slug": "tranquil-farmstay-wayanad",
        "description": "Tranquil Farmstay offers an immersive farm experience in the heart of Wayanad. Stay in comfortable eco-cottages.",
        "short_description": "Eco-farmstay with cottages, organic farming activities, and farm-fresh meals",
        "homestay_type": "farmstay",
        "host_name": "Ravi Kumar",
        "host_phone": "+91 94471 23456",
        "host_email": "tranquilfarm@gmail.com",
        "host_bio": "We are Ravi and Suma, passionate organic farmers.",
        "host_languages": ["Malayalam", "English", "Kannada"],
        "total_rooms": 3,
        "total_bathrooms": 3,
        "family_size": 4,
        "max_guests": 9,
        "price_per_night": "2800",
        "extra_person_charge": "600",
        "provides_meals": True,
        "meal_types": ["Breakfast", "Dinner"],
        "cooking_experience": True,
        "local_guide_service": False,
        "check_in_time": "13:00:00",
        "check_out_time": "11:00:00",
        "house_rules": "Eco-friendly practices encouraged. No plastic use.",
        "cancellation_policy": "Free cancellation up to 5 days before check-in.",
        "pet_friendly": True,
        "children_friendly": True,
        "elderly_friendly": True,
        "cultural_activities": ["Organic cooking workshop"],
        "farm_activities": ["Cow milking", "Vegetable harvesting"],
        "nearby_attractions": ["Banasura Dam 10km", "Meenmutty Falls 18km"],
        "address_line_1": "Padinjarathara Village",
        "city": "Kalpetta",
        "state": "Kerala",
        "postal_code": "673121",
        "country": "India",
        "latitude": "11.6234",
        "longitude": "76.0945",
        "cover_image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
        "gallery_images": ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
        "is_active": True,
        "is_featured": True,
        "is_verified": True,
        "commission_rate": "10.00",
    },
    {
        "name": "Tribal Heritage Home",
        "slug": "tribal-heritage-home-wayanad",
        "description": "Tribal Heritage Home offers a unique opportunity to experience the indigenous Adivasi culture of Wayanad.",
        "short_description": "Authentic tribal village homestay with traditional mud houses",
        "homestay_type": "village",
        "host_name": "Bomman Gowda",
        "host_phone": "+91 94472 34567",
        "host_email": "tribalhome@gmail.com",
        "host_bio": "I am Bomman, from the Paniya tribal community.",
        "host_languages": ["Malayalam", "Paniya", "English"],
        "total_rooms": 3,
        "total_bathrooms": 2,
        "family_size": 6,
        "max_guests": 8,
        "price_per_night": "2200",
        "extra_person_charge": "500",
        "provides_meals": True,
        "meal_types": ["Breakfast", "Lunch", "Dinner"],
        "cooking_experience": True,
        "local_guide_service": True,
        "check_in_time": "11:00:00",
        "check_out_time": "10:00:00",
        "house_rules": "Respect tribal customs. Photography only with permission.",
        "cancellation_policy": "Free cancellation up to 7 days before check-in.",
        "pet_friendly": False,
        "children_friendly": True,
        "elderly_friendly": False,
        "cultural_activities": ["Tribal dance", "Folklore storytelling"],
        "farm_activities": ["Forest honey collection", "Bamboo crafting"],
        "nearby_attractions": ["Kuruva Island 5km", "Thirunelli Temple 28km"],
        "address_line_1": "Mananthavady Tribal Settlement",
        "city": "Mananthavady",
        "state": "Kerala",
        "postal_code": "670645",
        "country": "India",
        "latitude": "11.8033",
        "longitude": "76.0044",
        "cover_image": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
        "gallery_images": ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800"],
        "is_active": True,
        "is_featured": True,
        "is_verified": True,
        "commission_rate": "8.00",
    },
]

print("Creating homestays...")
for data in homestays_data:
    Homestay.objects.create(**data)
print(f"Created {len(homestays_data)} homestays!")

print("\nData loading complete!")
print(f"Total Resorts: {Resort.objects.count()}")
print(f"Total Homestays: {Homestay.objects.count()}")
