# Generated by Django 5.0.2 on 2025-10-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "address_line_1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(
                        default="Kerala", max_length=100, verbose_name="state"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="postal code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is featured"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=320, verbose_name="meta description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="meta keywords"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "short_description",
                    models.CharField(max_length=500, verbose_name="short description"),
                ),
                (
                    "resort_type",
                    models.CharField(
                        choices=[
                            ("luxury", "Luxury Resort"),
                            ("boutique", "Boutique Resort"),
                            ("eco", "Eco Resort"),
                            ("family", "Family Resort"),
                            ("adventure", "Adventure Resort"),
                        ],
                        max_length=20,
                        verbose_name="resort type",
                    ),
                ),
                (
                    "star_rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="star rating",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "total_rooms",
                    models.PositiveIntegerField(verbose_name="total rooms"),
                ),
                (
                    "property_size",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="property size"
                    ),
                ),
                (
                    "year_established",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year established"
                    ),
                ),
                (
                    "price_range_min",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="minimum price"
                    ),
                ),
                (
                    "price_range_max",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="maximum price"
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(default="14:00", verbose_name="check-in time"),
                ),
                (
                    "check_out_time",
                    models.TimeField(default="11:00", verbose_name="check-out time"),
                ),
                (
                    "cancellation_policy",
                    models.TextField(verbose_name="cancellation policy"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="resorts/covers/", verbose_name="cover image"
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="gallery images"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="is verified"),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="commission rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resort",
                "verbose_name_plural": "Resorts",
                "db_table": "resorts",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResortAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="amenity name"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recreation", "Recreation"),
                            ("dining", "Dining"),
                            ("wellness", "Wellness & Spa"),
                            ("business", "Business"),
                            ("family", "Family & Kids"),
                            ("outdoor", "Outdoor Activities"),
                            ("transport", "Transportation"),
                            ("services", "Services"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="icon class"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "Resort Amenity",
                "verbose_name_plural": "Resort Amenities",
                "db_table": "resort_amenities",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Room"),
                            ("deluxe", "Deluxe Room"),
                            ("suite", "Suite"),
                            ("villa", "Villa"),
                            ("cottage", "Cottage"),
                            ("treehouse", "Treehouse"),
                        ],
                        max_length=20,
                        verbose_name="room type",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="room size"
                    ),
                ),
                (
                    "max_occupancy",
                    models.PositiveIntegerField(
                        default=2, verbose_name="maximum occupancy"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="base price per night",
                    ),
                ),
                (
                    "weekend_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="weekend price per night",
                    ),
                ),
                (
                    "peak_season_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="peak season price",
                    ),
                ),
                (
                    "total_rooms",
                    models.PositiveIntegerField(
                        default=1, verbose_name="total rooms of this type"
                    ),
                ),
                (
                    "bed_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="bed type"
                    ),
                ),
                (
                    "has_ac",
                    models.BooleanField(default=True, verbose_name="air conditioning"),
                ),
                ("has_wifi", models.BooleanField(default=True, verbose_name="wifi")),
                (
                    "has_tv",
                    models.BooleanField(default=True, verbose_name="television"),
                ),
                (
                    "has_balcony",
                    models.BooleanField(default=False, verbose_name="balcony"),
                ),
                (
                    "has_bathtub",
                    models.BooleanField(default=False, verbose_name="bathtub"),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="room images"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="resorts.resort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Type",
                "verbose_name_plural": "Room Types",
                "db_table": "resort_room_types",
                "unique_together": {("resort", "slug")},
            },
        ),
        migrations.CreateModel(
            name="SeasonalPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "season_name",
                    models.CharField(max_length=100, verbose_name="season name"),
                ),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("peak", "Peak Season"),
                            ("high", "High Season"),
                            ("normal", "Normal Season"),
                            ("low", "Low Season"),
                        ],
                        max_length=10,
                        verbose_name="season type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "price_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=4,
                        verbose_name="price multiplier",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="fixed price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_pricing",
                        to="resorts.resort",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_pricing",
                        to="resorts.roomtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seasonal Pricing",
                "verbose_name_plural": "Seasonal Pricing",
                "db_table": "resort_seasonal_pricing",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="ResortAmenityMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured amenity"),
                ),
                (
                    "additional_info",
                    models.TextField(blank=True, verbose_name="additional information"),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resorts.resortamenity",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_mappings",
                        to="resorts.resort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resort Amenity Mapping",
                "verbose_name_plural": "Resort Amenity Mappings",
                "db_table": "resort_amenity_mappings",
                "unique_together": {("resort", "amenity")},
            },
        ),
    ]
