# Generated by Django 5.0.2 on 2025-10-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is featured"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=320, verbose_name="meta description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="meta keywords"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel_guide", "Travel Guide"),
                            ("local_culture", "Local Culture"),
                            ("adventure", "Adventure"),
                            ("food", "Food & Cuisine"),
                            ("events", "Events & Festivals"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("excerpt", models.TextField(max_length=500, verbose_name="excerpt")),
                (
                    "featured_image",
                    models.ImageField(
                        upload_to="blog/featured/", verbose_name="featured image"
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        default=5, verbose_name="reading time in minutes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "db_table": "blog_posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
