# Generated by Django 5.0.2 on 2025-10-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("resort", "Resort"),
                            ("homestay", "Homestay"),
                            ("vehicle", "Vehicle"),
                            ("destination", "Destination"),
                            ("activity", "Activity"),
                        ],
                        max_length=20,
                        verbose_name="content type",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="rating",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="review title"),
                ),
                ("comment", models.TextField(verbose_name="comment")),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="review images"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="is approved"),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="moderated at"
                    ),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="helpful count"
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
