# Generated by Django 5.0.2 on 2025-10-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="gateway name")),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("payu", "PayU"),
                        ],
                        max_length=20,
                        verbose_name="gateway type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(default=True, verbose_name="test mode"),
                ),
                ("public_key", models.TextField(blank=True, verbose_name="public key")),
                ("secret_key", models.TextField(blank=True, verbose_name="secret key")),
                (
                    "transaction_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="transaction fee %",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Gateway",
                "verbose_name_plural": "Payment Gateways",
                "db_table": "payment_gateways",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="transaction ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="gateway transaction ID",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="gateway response"
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.paymentgateway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
