# Generated by Django 5.0.2 on 2025-10-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "address_line_1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(
                        default="Kerala", max_length=100, verbose_name="state"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="postal code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is featured"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=320, verbose_name="meta description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="meta keywords"
                    ),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("waterfall", "Waterfall"),
                            ("trek", "Trekking Trail"),
                            ("wildlife", "Wildlife Sanctuary"),
                            ("adventure", "Adventure Activity"),
                            ("cultural", "Cultural Site"),
                            ("viewpoint", "Scenic Viewpoint"),
                        ],
                        max_length=20,
                        verbose_name="destination type",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "short_description",
                    models.CharField(max_length=500, verbose_name="short description"),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="entry fee",
                    ),
                ),
                (
                    "is_free_entry",
                    models.BooleanField(default=False, verbose_name="free entry"),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="opening time"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="closing time"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="destinations/covers/", verbose_name="cover image"
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="gallery images"
                    ),
                ),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
                "db_table": "destinations",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is featured"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("trekking", "Trekking"),
                            ("boating", "Boating"),
                            ("zip_line", "Zip Lining"),
                            ("camping", "Camping"),
                            ("safari", "Wildlife Safari"),
                        ],
                        max_length=20,
                        verbose_name="activity type",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="duration in hours"
                    ),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="price per person"
                    ),
                ),
                (
                    "child_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="child price",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=20, verbose_name="max participants per slot"
                    ),
                ),
                (
                    "advance_booking_hours",
                    models.PositiveIntegerField(
                        default=2, verbose_name="advance booking hours"
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="destinations.destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "destination_activities",
            },
        ),
    ]
