# Generated by Django 5.0.2 on 2025-10-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='google_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Google Places data'),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last synced with Google'),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps URL'),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone from Google'),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Google Place ID'),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Google rating'),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_total_ratings',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='total Google ratings'),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_website',
            field=models.URLField(blank=True, null=True, verbose_name='website from Google'),
        ),
    ]
