# Generated by Django 5.0.2 on 2025-10-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homestay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "address_line_1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(
                        default="Kerala", max_length=100, verbose_name="state"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="postal code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is featured"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=320, verbose_name="meta description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="meta keywords"
                    ),
                ),
                (
                    "host_name",
                    models.CharField(max_length=100, verbose_name="host name"),
                ),
                (
                    "host_phone",
                    models.CharField(max_length=20, verbose_name="host phone"),
                ),
                (
                    "host_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="host email"
                    ),
                ),
                ("host_bio", models.TextField(blank=True, verbose_name="host bio")),
                (
                    "host_languages",
                    models.JSONField(
                        blank=True, default=list, verbose_name="languages spoken"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "short_description",
                    models.CharField(max_length=500, verbose_name="short description"),
                ),
                (
                    "homestay_type",
                    models.CharField(
                        choices=[
                            ("traditional", "Traditional Home"),
                            ("farmstay", "Farm Stay"),
                            ("village", "Village Home"),
                            ("heritage", "Heritage Home"),
                            ("eco", "Eco Home"),
                        ],
                        max_length=20,
                        verbose_name="homestay type",
                    ),
                ),
                (
                    "total_rooms",
                    models.PositiveIntegerField(verbose_name="total guest rooms"),
                ),
                (
                    "total_bathrooms",
                    models.PositiveIntegerField(
                        default=1, verbose_name="total bathrooms"
                    ),
                ),
                (
                    "house_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="house age in years"
                    ),
                ),
                (
                    "family_size",
                    models.PositiveIntegerField(default=4, verbose_name="family size"),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        default=4, verbose_name="maximum guests"
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="price per night"
                    ),
                ),
                (
                    "extra_person_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="extra person charge",
                    ),
                ),
                (
                    "provides_meals",
                    models.BooleanField(default=True, verbose_name="provides meals"),
                ),
                (
                    "meal_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="meal types available"
                    ),
                ),
                (
                    "cooking_experience",
                    models.BooleanField(
                        default=False, verbose_name="cooking experience available"
                    ),
                ),
                (
                    "local_guide_service",
                    models.BooleanField(
                        default=False, verbose_name="local guide service"
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(default="14:00", verbose_name="check-in time"),
                ),
                (
                    "check_out_time",
                    models.TimeField(default="11:00", verbose_name="check-out time"),
                ),
                (
                    "house_rules",
                    models.TextField(blank=True, verbose_name="house rules"),
                ),
                (
                    "cancellation_policy",
                    models.TextField(verbose_name="cancellation policy"),
                ),
                (
                    "pet_friendly",
                    models.BooleanField(default=False, verbose_name="pet friendly"),
                ),
                (
                    "children_friendly",
                    models.BooleanField(default=True, verbose_name="children friendly"),
                ),
                (
                    "elderly_friendly",
                    models.BooleanField(default=True, verbose_name="elderly friendly"),
                ),
                (
                    "cultural_activities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="cultural activities"
                    ),
                ),
                (
                    "farm_activities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="farm activities"
                    ),
                ),
                (
                    "nearby_attractions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="nearby attractions"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="homestays/covers/", verbose_name="cover image"
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="gallery images"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="is verified"),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=5,
                        verbose_name="commission rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homestay",
                "verbose_name_plural": "Homestays",
                "db_table": "homestays",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomestayAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="amenity name"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Amenities"),
                            ("kitchen", "Kitchen & Dining"),
                            ("outdoor", "Outdoor Areas"),
                            ("entertainment", "Entertainment"),
                            ("services", "Services"),
                            ("safety", "Safety & Security"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="icon class"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "Homestay Amenity",
                "verbose_name_plural": "Homestay Amenities",
                "db_table": "homestay_amenities",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="HomestayRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "room_name",
                    models.CharField(max_length=100, verbose_name="room name"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Room"),
                            ("double", "Double Room"),
                            ("family", "Family Room"),
                            ("shared", "Shared Room"),
                            ("dormitory", "Dormitory"),
                        ],
                        max_length=20,
                        verbose_name="room type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "max_occupancy",
                    models.PositiveIntegerField(
                        default=2, verbose_name="maximum occupancy"
                    ),
                ),
                (
                    "bed_configuration",
                    models.CharField(max_length=200, verbose_name="bed configuration"),
                ),
                (
                    "has_ac",
                    models.BooleanField(default=False, verbose_name="air conditioning"),
                ),
                (
                    "has_fan",
                    models.BooleanField(default=True, verbose_name="ceiling fan"),
                ),
                ("has_wifi", models.BooleanField(default=True, verbose_name="wifi")),
                (
                    "has_attached_bathroom",
                    models.BooleanField(
                        default=False, verbose_name="attached bathroom"
                    ),
                ),
                (
                    "has_balcony",
                    models.BooleanField(default=False, verbose_name="balcony"),
                ),
                (
                    "has_study_table",
                    models.BooleanField(default=False, verbose_name="study table"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="base price per night",
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="room images"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="homestays.homestay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homestay Room",
                "verbose_name_plural": "Homestay Rooms",
                "db_table": "homestay_rooms",
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "plan_name",
                    models.CharField(max_length=100, verbose_name="plan name"),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast Only"),
                            ("half_board", "Half Board (Breakfast + Dinner)"),
                            ("full_board", "Full Board (All Meals)"),
                            ("custom", "Custom Plan"),
                        ],
                        max_length=20,
                        verbose_name="meal type",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="price per person per day",
                    ),
                ),
                (
                    "child_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="child price (under 12)",
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        default="Traditional Kerala",
                        max_length=100,
                        verbose_name="cuisine type",
                    ),
                ),
                (
                    "dietary_options",
                    models.JSONField(
                        blank=True, default=list, verbose_name="dietary options"
                    ),
                ),
                (
                    "special_dishes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="special dishes"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "advance_notice_hours",
                    models.PositiveIntegerField(
                        default=2, verbose_name="advance notice required (hours)"
                    ),
                ),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to="homestays.homestay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Plan",
                "verbose_name_plural": "Meal Plans",
                "db_table": "homestay_meal_plans",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("cultural", "Cultural Experience"),
                            ("cooking", "Cooking Class"),
                            ("farming", "Farm Activity"),
                            ("craft", "Traditional Craft"),
                            ("nature", "Nature Walk"),
                            ("spiritual", "Spiritual Experience"),
                        ],
                        max_length=20,
                        verbose_name="experience type",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="duration in hours"
                    ),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="price per person"
                    ),
                ),
                (
                    "minimum_participants",
                    models.PositiveIntegerField(
                        default=1, verbose_name="minimum participants"
                    ),
                ),
                (
                    "maximum_participants",
                    models.PositiveIntegerField(
                        default=10, verbose_name="maximum participants"
                    ),
                ),
                (
                    "age_restriction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="age restriction"
                    ),
                ),
                (
                    "fitness_level",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="fitness level required",
                    ),
                ),
                (
                    "equipment_provided",
                    models.BooleanField(
                        default=True, verbose_name="equipment provided"
                    ),
                ),
                (
                    "equipment_list",
                    models.JSONField(
                        blank=True, default=list, verbose_name="equipment list"
                    ),
                ),
                (
                    "available_times",
                    models.JSONField(
                        blank=True, default=list, verbose_name="available times"
                    ),
                ),
                (
                    "advance_booking_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="advance booking required (days)"
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="experience images"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="homestays.homestay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "db_table": "homestay_experiences",
                "unique_together": {("homestay", "slug")},
            },
        ),
        migrations.CreateModel(
            name="HomestayAmenityMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured amenity"),
                ),
                (
                    "additional_info",
                    models.TextField(blank=True, verbose_name="additional information"),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homestays.homestayamenity",
                    ),
                ),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_mappings",
                        to="homestays.homestay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homestay Amenity Mapping",
                "verbose_name_plural": "Homestay Amenity Mappings",
                "db_table": "homestay_amenity_mappings",
                "unique_together": {("homestay", "amenity")},
            },
        ),
    ]
