# Generated by Django 5.0.2 on 2025-10-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homestayamenity',
            options={'ordering': ['category', '-display_priority', 'name'], 'verbose_name': 'Homestay Amenity', 'verbose_name_plural': 'Homestay Amenities'},
        ),
        migrations.AddField(
            model_name='homestayamenity',
            name='amenity_type',
            field=models.CharField(choices=[('boolean', 'Yes/No'), ('count', 'Count'), ('text', 'Text Description'), ('list', 'Multiple Options')], default='boolean', max_length=20, verbose_name='amenity type'),
        ),
        migrations.AddField(
            model_name='homestayamenity',
            name='display_priority',
            field=models.PositiveIntegerField(default=0, verbose_name='display priority'),
        ),
        migrations.AddField(
            model_name='homestayamenity',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='premium amenity'),
        ),
        migrations.AddField(
            model_name='homestayamenitymapping',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='currently available'),
        ),
        migrations.AddField(
            model_name='homestayamenitymapping',
            name='value',
            field=models.JSONField(blank=True, default=dict, verbose_name='amenity value'),
        ),
        migrations.AlterField(
            model_name='homestayamenity',
            name='category',
            field=models.CharField(choices=[('property', 'Property Features'), ('room', 'Room Features'), ('services', 'Services'), ('dining', 'Dining'), ('activities', 'Activities'), ('safety', 'Safety & Security'), ('outdoor', 'Outdoor Areas'), ('entertainment', 'Entertainment'), ('kitchen', 'Kitchen & Dining')], max_length=20, verbose_name='category'),
        ),
    ]
